language: python
python:
  - "3.6"
  - "3.7"
services:
  - docker
install:
  - make install
  - make install-dev
  - docker pull jdkato/vale
script:
  - make lint
  - make test
  - make website
  - make lint-docs
