# Used for testing
---
version: '3'
services:
  db:
    image: postgres
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_DB: taskforge
      POSTGRES_USER: taskforge
      POSTGRES_PASSWORD: taskforge

  api:
    image: taskforge/backend:latest
    depends_on:
      - "db"
    ports:
      - 127.0.0.1:8000:8000
    environment:
      TASKFORGE_HOST: 0.0.0.0
      PGHOST: db
      PGPASSWORD: taskforge
