# Used for testing
---
version: '3'
services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: taskforge
            POSTGRES_USER: taskforge
            POSTGRES_PASSWORD: taskforge

    migrations:
        image: taskforge/backend:latest
        depends_on:
            - 'db'
        environment:
            MIGRATE: 1
            TASKFORGE_DB_HOST: db

    api:
        image: taskforge/backend:latest
        depends_on:
            - 'migrations'
        ports:
            - 127.0.0.1:8000:8000
        environment:
            TASKFORGE_DB_HOST: db
