# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  docs-validate-links:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install pylinkvalidator
          command: pip install pylinkvalidator
      - run:
          name: Validate links
          command:
            make docker-website
            make lint-docs-validate-links

  docs-lint:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Lint docs with vale
          command: make lint-docs-vale
    
  lint:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repository
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flake8 pydocstyle isort black
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            python -m flake8 src tests
      - run:
          name: check docstring style
          command: |
            . venv/bin/activate
            python -m pydocstyle src
      - run:
          name: check formatting
          command: |
            . venv/bin/activate
            python -m isort --recursive --check-only src tests
            python -m black --check src tests
    
  test: &test-template
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements/runtime.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install-dev

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements/runtime.txt" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test

      - store_artifacts:
          path: test-reports
          destination: test-reports

  test-3.7:
    <<: *test-template
    docker:
      - image: circleci/python:3.7

  test-3.8:
    <<: *test-template
    docker:
      - image: circleci/python:3.8

