---
name: Test

on: push

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run tests
        run: |
          npm test
          code=$?
          if [[ $code -ne 0 ]]; then
              docker logs api
          fi
          exit $code
        env:
          TASKFORGE_HOST: https://api.test.taskforge.io/api
